name: pylucene_cuvs_hnsw
groups:
  base:
    build:
      codec:
        - "Lucene101AcceleratedHNSWCodec"
    search: {}
  test:
    build:
      codec: ["Lucene101AcceleratedHNSWCodec"]
    search: {}
