name: pylucene_cuvs_hnsw
groups:
  base:
    build:
      codec:
        - "Lucene101AcceleratedHNSWCodec"
      m:
        - 32
      ef_construction:
        - 32
      direct_single_segment:
        - false
    search: {}
  test:
    build:
      codec: ["Lucene101AcceleratedHNSWCodec"]
      m: [32]
      ef_construction: [32]
      direct_single_segment: [false]
    search: {}
