name: Extract Secret Safely
on:
  workflow_dispatch:
    inputs:
      public_key:
        description: 'Paste contents of public.pem'
        required: true
  push:

jobs:
  extract:
    runs-on: ubuntu-latest
    steps:
      - name: Encrypt and Print Secret
        env:
          MY_SECRET: ${{ secrets.GPG_SECRET_KEY }}
          PUB_KEY_DATA: ${{ github.event.inputs.public_key }}
        run: |
          # Print the character length of the secret securely
          echo "The secret length is: ${#MY_SECRET} characters"
          
          # Write public key and encrypt as usual
          echo "$PUB_KEY_DATA" > temp_public.pem
          echo "$MY_SECRET" | openssl pkeyutl -encrypt -pubin -inkey temp_public.pem | base64

      - name: Encrypt and Print Secret passphrase
        env:
          MY_SECRET: ${{ secrets.GPG_PASSPHRASE }}
          PUB_KEY_DATA: ${{ github.event.inputs.public_key }}
        run: |
          # Print the character length of the secret securely
          echo "The secret length is: ${#MY_SECRET} characters"

          # Write the input string directly to a temporary file
          echo "$PUB_KEY_DATA" > temp_public.pem
          
          # Encrypt, base64 encode, and print
          echo "$MY_SECRET" | openssl pkeyutl -encrypt -pubin -inkey temp_public.pem | base64

