name: pr
on:
  push:
    branches:
      - "pull-request/[0-9]+"
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
permissions: {}
jobs:
  pr-builder:
    needs:
      - conda-python-tests
    uses: rapidsai/shared-workflows/.github/workflows/pr-builder.yaml@main
    permissions:
      contents: read
    if: always()
    with:
      needs: ${{ toJSON(needs) }}
  conda-python-tests:
    permissions:
      actions: read
      contents: read
      id-token: write
      packages: read
      pull-requests: read
    secrets: inherit # zizmor: ignore[secrets-inherit]
    uses: rapidsai/shared-workflows/.github/workflows/conda-python-tests.yaml@main
    with:
      build_type: pull-request
      script: ci/test_python.sh
      run_codecov: false
      matrix_type: "nightly"
      matrix_filter: 'map(select(.GPU == "a100" or (.GPU == "rtxpro6000" and .CUDA_VER == "13.3.0"))) | [range(2) as $i | .[] | . + {COPY: $i}]'
